### PR TITLE
Fix integer overflow of number_of_point_records when using laszip_update_inventory

### PR DESCRIPTION
**Pull request by VxGrid**
When writing more than 2^32 points while using the function laszip_update_inventory, an integer overflow will happen.
So using LAS format 1.4 in conjunction with point data record format 6 or higher is not conform to the specified standard.
This commit fixes that issue and in addition will notify the user if an overflow happens in LAS format 1.2

### CODE REVIEW

**Comment by hobu** [comment]
Doesn't this change break everyone's usage of the DLL? `laszip_dll_inventory` had U32 values for those items. The change should instead ADD U64 entries and update both, correct?

**Comment by VxGrid** [comment]
> Doesn't this change break everyone's usage of the DLL? `laszip_dll_inventory` had U32 values for those items. The change should instead ADD U64 entries and update both, correct?

Not to out me as being oblivious or ignorant, but could you please elaborate?

The changes are only affecting internal stuff, so the interface didn't change, only internal calls, which are getting resolved directly in the dll.

To be sure I just tested the following cases by creating a LAS file with the update_inventory function with the following cases:

- Using the previous compiled dll while linking against the new commit, 
- Using the previous compiled dll while linking against the previous commit,
- Using the new dll while linking against the new commit,
- Using the new dll while linking against the previous commit.

Resulting LAS was readable in CloudCompare in all 4 cases.


All what should happen for introducing the new dll, is that an internal U32 field is now an U64 field which won't get an integer overflow when writing more than 2^32 points. I can't imagine a use case where this is would have been wanted behavior.

From a usage perspective this shouldn't change the result:
- Writing LAS 1.2, standard is that the number records must be smaller than 2^32 points, if too many points are written update_inventory will fail. If this was wanted behaviour, it was already misuse of the standard. (Like writing more points and ignoring the number_of_point_records field).
- Writing LAS 1.4 will now work as intended (writing more than 2^32 points is now possible using the function without just saving the overflown number).

**Comment by hobu** [comment]
> is that an internal U32 field is now an U64 field which won't get an integer overflow when writing more than 2^32 points. 

`number_of_point_records` and `number_of_points_by_return` are `public` fields of the `laszip_dll_inventory` class, so if anyone was using them, they need to update their code or accept the conversion. In this particular case it is not a big change, but if the policy of LASzip going forward is to change public interface members at will without any deprecation or notice, that should be articulated in a stronger way. 

It's too bad we could never convince Martin about automated testing 😦

**Comment by tkircher** [comment]
It doesn't look like those variables are intended to be accessed directly through the API, since there are well-defined interfaces already.

**Comment by thbeu** [comment]
> It doesn't look like those variables are intended to be accessed directly through the API, since there are well-defined interfaces already.

In that case they should not be public - which means another breaking change if set to private.

**Pull request merged**
