### PR TITLE
Add utf8 supported filepath for windows

### PR DESCRIPTION
**Pull request by Madrich**
On windows platform fopen can not handle utf8 based filepaths. This code uses wfopen with utf16. So we need to convert first.

### CODE REVIEW

**Comment by hobu** [comment]
Thanks for patch, but there's a few issues:

- It doesn't compile on Linux https://travis-ci.org/LASzip/LASzip/jobs/287945775
- The upstream for this code is LAStools, and it should more properly go there. @rapidlasso uses MSVC6 as a compiler, so any patches would need to compile and execute cleanly on that platform.

**Comment by Madrich** [comment]
Dear Howard,

you are right. There was a missing "#include <vector>" for linux 
compiler and I fixed it already.
The microsoft compiler msvc 6 soport wfopen. My code will compile there too.

Best regards, Richard

**Comment by hobu** [comment]
@rapidlasso Can you merge this to the upstream LASzip codebase?

**Comment by rapidlasso** [comment]
I believe this pull request is result of my INTERGEO show floor activity to assure the v4 readers are in place. But I left the next day to Asia and I have not had the time to look at this yet. Greetings from Singapore.

**Comment by rapidlasso** [comment]
Could you undo the file name change in "dll/laszip_api.c". The Windows DLLs are called "LASzip.dll" and "LASzip64.dll".

**Comment by Madrich** [comment]
Hi Martin.

When I compiled the new laszip on Windows, the resulting dll name is
laszip3.dll automatically. I don't know where does it comes from.

Richard

Martin Isenburg <notifications@github.com> schrieb am Sa., 28. Sep. 2019,
14:01:

**Comment by hobu** [comment]
I made the dll name change for the standalone library. There was no versioning in old dlls and they were getting loaded at the incorrect time based on linkage.

**Comment by rapidlasso** [comment]
I have implemented this functionality slightly differently. This is now in the source. Could you check if these commits do the trick for you: 
https://github.com/LASzip/LASzip/commit/6ab326a8f0c95b6427d900ca4a076abcd01eda0c
https://github.com/LASzip/LASzip/commit/8d23ed153147ee9d1011a918002fda1bbbce2cb1
https://github.com/LASzip/LASzip/commit/ee8a0d94de07a800689dff0730b6ea0475dbf2ba

**Comment by rapidlasso** [comment]
Three different parties requested the same thing for LASzip and LASlib and I took all their suggestions and compiled them into a minimalist solution hidden behind Windows #ifdefs. It's the smallest change that I could come up with. That said ... I would be happy to move this out of laszip.hpp and laszip.cpp into a separate helper file if you would prefer that ... ?

**Comment by rapidlasso** [comment]
@hobu as per your suggestion I moved the UTF8toUTF16 method from laszip.hpp to mydefs.hpp in this commit: https://github.com/LASzip/LASzip/commit/ac1921a89a0f15e61e58df9cde5477fabad0241c

**Pull request closed without merging**
