### PR TITLE
Fixes for compilation w/clang OSX. Fix for VLR header stream.

### PR DESCRIPTION
**Pull request by abellgithub**
These changes allow laszip to pass PDAL compression/decompression tests.

### CODE REVIEW

**Comment by hobu** [comment]
@rapidlasso can we merge these items?

**Comment by rapidlasso** [comment]
First time I notice that fix. Sometimes it helps to ping me immediately. Some notifications I do not seem to get ... strange. Let me see how badly this breaks things for me ... (-;

**Comment by hobu** [comment]
Are you ready for a LASzip.or release?

**Comment by abellgithub** [comment]
Should we indicate the version of the release in the code so that it can be determined statically?  Other thoughts on this?

**Comment by rapidlasso** [comment]
Give me another day or so.

**Comment by rapidlasso** [comment]
I think the DLL is still fully compatible with all prior releases and there is a function to query the version.

**Comment by abellgithub** [comment]
Right, but for our code, we need the added new functions.  I guess we could search the header for them.  That strikes me as ugly, but maybe that's just me.

**Comment by rapidlasso** [comment]
We can increment the minor version?

**Comment by rapidlasso** [comment]
This version does work now for both me and you ... but we should maybe wait until full (with and without header) C++ stream write support is implemented to make a new release. A few more days (just en-route back to my tropical labs in Costa Rica). If you need it quick (as a release) we could make an intermediary release? Or can you wait another week?

**Pull request merged**
