### PR TITLE
Fix GCC Warnings

### PR DESCRIPTION
**Pull request by JoseGoncalves**
This pull request fixes several warnings that appear when compiling LASzip with GCC 8.3 in Linux.

### CODE REVIEW

**Comment by rapidlasso** [comment]
That's a lot of changes. Will take me a (longer) while to review.

**Comment by JoseGoncalves** [comment]
While there are a lot of changes, the biggest part is related with the same unique cause that is addressed in commit 8f6aa3e, i.e., casts that discard a const qualifier. 
Here are some examples of such warnings:
```
[ 34%] Building CXX object src/CMakeFiles/laszip.dir/lasreaditemcompressed_v1.cpp.o
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v1.cpp: In member function ‘virtual BOOL LASreadItemCompressed_GPSTIME11_v1::init(const U8*, U32&)’:
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v1.cpp:291:30: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘U64*’ {aka ‘long long unsigned int*’} casts away qualifiers [-Wcast-qual]
   last_gpstime.u64 = *((U64*)item);
                              ^~~~
[ 39%] Building CXX object src/CMakeFiles/laszip.dir/lasreaditemcompressed_v2.cpp.o
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v2.cpp: In member function ‘virtual BOOL LASreadItemCompressed_GPSTIME11_v2::init(const U8*, U32&)’:
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v2.cpp:290:33: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘U64*’ {aka ‘long long unsigned int*’} casts away qualifiers [-Wcast-qual]
   last_gpstime[0].u64 = *((U64*)item);
                                 ^~~~
[ 43%] Building CXX object src/CMakeFiles/laszip.dir/lasreaditemcompressed_v3.cpp.o
In file included from /home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.hpp:40,
                 from /home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp:32:
/home/jmpg/MPP/LASzip.upstream/src/bytestreamin_array.hpp: In member function ‘virtual void ByteStreamInArray::getBytes(U8*, U32)’:
/home/jmpg/MPP/LASzip.upstream/src/bytestreamin_array.hpp:154:41: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘void*’ casts away qualifiers [-Wcast-qual]
   memcpy((void*)bytes, (void*)(data+curr), num_bytes);
                                         ^
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp: In member function ‘BOOL LASreadItemCompressed_POINT14_v3::createAndInitModelsAndDecompressors(U32, const U8*)’:
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp:324:49: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘LASpoint14*’ casts away qualifiers [-Wcast-qual]
     contexts[context].last_Z[i] = ((LASpoint14*)item)->Z;
                                                 ^~~~
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp:343:57: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘LASpoint14*’ casts away qualifiers [-Wcast-qual]
     contexts[context].last_intensity[i] = ((LASpoint14*)item)->intensity;
                                                         ^~~~
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp:368:57: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘LASpoint14*’ casts away qualifiers [-Wcast-qual]
   contexts[context].last_gpstime[0].f64 = ((LASpoint14*)item)->gps_time;
                                                         ^~~~
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp: In member function ‘virtual BOOL LASreadItemCompressed_POINT14_v3::init(const U8*, U32&)’:
/home/jmpg/MPP/LASzip.upstream/src/lasreaditemcompressed_v3.cpp:696:35: warning: cast from type ‘const U8*’ {aka ‘const unsigned char*’} to type ‘LASpoint14*’ casts away qualifiers [-Wcast-qual]
   current_context = ((LASpoint14*)item)->scanner_channel;
                                   ^~~~
```

**Comment by JoseGoncalves** [comment]
While compling in Debian 10 (also with GCC 8) a couple of extra warnings are triggered (previously I was compiling in Ubuntu 18.04).
One is a possible use of an unitialized value in a fprintf that is addressed in commit 2947ee6e189eebbadd31782e27430f83f34a1bd9.
The others are related with uses of `strncpy` that can lead to strings not NULL terminated:
```
[ 82%] Building CXX object src/CMakeFiles/laszip.dir/laszip_dll.cpp.o
/home/jmpg/LASzip/src/laszip_dll.cpp: In function ‘laszip_I32 laszip_add_vlr(laszip_POINTER, const laszip_CHAR*, laszip_U16, laszip_U16, const laszip_CHAR*, const laszip_U8*)’:
/home/jmpg/LASzip/src/laszip_dll.cpp:1503:12: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 16 equals destination size [-Wstringop-truncation]
     strncpy(laszip_dll->header.vlrs[i].user_id, user_id, 16);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/jmpg/LASzip/src/laszip_dll.cpp:1508:14: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
       strncpy(laszip_dll->header.vlrs[i].description, description, 32);
       ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jmpg/LASzip/src/laszip_dll.cpp:61:
In constructor ‘LASattribute::LASattribute(U32, const CHAR*, const CHAR*)’,
    inlined from ‘laszip_I32 laszip_add_attribute(laszip_POINTER, laszip_U32, const laszip_CHAR*, const laszip_CHAR*, laszip_F64, laszip_F64)’ at /home/jmpg/LASzip/src/laszip_dll.cpp:1373:54:
/home/jmpg/LASzip/src/lasattributer.hpp:79:12: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
     strncpy(this->name, name, 32);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
/home/jmpg/LASzip/src/lasattributer.hpp:80:29: warning: ‘char* strncpy(char*, const char*, size_t)’ specified bound 32 equals destination size [-Wstringop-truncation]
     if (description) strncpy(this->description, description, 32);
                      ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Is it OK for fields `user_id` and `description` in the VLR not to be NULL terminated?

**Comment by dwilliamsND** [comment]
@JoseGoncalves 
Correct me if I'm wrong, but doesn't `std::strncpy` guarantee a null-terminator? 
(the limiting character count would include the space for the `\0`)

**Comment by tkircher** [comment]
@dwilliamsND

https://en.cppreference.com/w/cpp/string/byte/strncpy

**Comment by dwilliamsND** [comment]
For other readers, the spec of strncpy specifies:
> If count is reached before the entire string src was copied, the resulting character array is not null-terminated.
(from en.cppreference.com )

**Pull request closed without merging**
